#spring:
#  datasource:
#    url: jdbc:mysql://laomedia.cffhqwuildxe.us-east-1.rds.amazonaws.com
#    uername: admin
#    password: Thisisatestdatabase
#    databaseName: "-"
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    profile: JTASSONE
    region:
      static: us-east-1
    stack:
      auto: false
    rds:
      laomedia:
        databaseName: "-"
        username: admin
        password: Thisisatestdatabase
spring:
  jpa:
    hibernate:
      ddl-auto: create