#spring:
#  datasource:
#    url: jdbc:mysql://laomedia.cffhqwuildxe.us-east-1.rds.amazonaws.com
#    uername: admin
#    password: Thisisatestdatabase
#    databaseName: "-"
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      auto: false
      static: us-east-1
    credentials:
      profile-name: JTASSONE
    stack:
      auto: false
    rds:
      laomedia:
        db-instance-identifier: laomedia
        databaseName: laoData
        username: admin
        password: Thisisatestdatabase
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create